### ISSUE TITLE
The integration doesn't seem to work

### ISSUE THREAD

**Issue by dula34** [markvader/ha-rpi_rf#127]
HW: Rpi3

Home Assistant 2023.10.5
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231005.0 - latest

my configuration
```
switch:
  - platform: rpi_rf
    gpio: 17
    switches:
      bell:
        signal_repetitions: 1
        pulselength: 388
        code_on: 3010305
        code_off: 3010305
        unique_id: "custom_unique_id"
```
